service: chatTest # provide the project name
provider:
  name: aws
  runtime: java8



package:
  artifact: target/chatTest-0.0.1-SNAPSHOT.jar # provide path of the jar file

functions:
  getRoom:
    handler: com.websocket.chattest.config.StreamLambdaHandler::handleRequest
    events:
      - websocket:
          route: $connect
          cors: true
      - http:
          path: /roomNum/{roomNum}
          method: get
          cors: true
